### ISSUE TITLE
Blue/Red Example invalid deck code?

### ISSUE THREAD

**Issue by iScrE4m** [ValveSoftware/ArtifactDeckCode#15] opened 2018-11-13 13:41 UTC
Hi, I'm in the process of porting and wrapping the API in python. I started with Green/Black and managed to decode the string succesfully, but when I added Blue/Red into the example, it seems to have something to have two extra cards encoded: `{'id': 10427, 'count': 2}`.

10427 isn't a card available in the API and the rest of the deck seems to be correct (I'm not missing anything compared to web viewer nor do I have any counts wrong). 

Can anyone else confirm this? Is this intended and will happen with upcoming sets when there are unannounced cards?

**Comment by JeffAtValve** [comment] 2018-11-13 13:48
It looks like you have a bug somewhere.  The highest card value in that deck is 10223 and it has 20 card entries (they will be sorted).

**Comment by iScrE4m** [comment] 2018-11-13 13:59
Thanks for ensuring me, I'll dive back into it :)

**Comment by MisterJimson** [comment] 2018-11-13 14:08
Note that deckBytes in CArtifactDeckDecoder is a 1 based array, not 0. That was tricky for me when converting to C#.

**Comment by iScrE4m** [comment] 2018-11-13 16:09
In python, iterating from 0 seems to work, if I start at 1, I end up with version missmatch. Everything else is exactly as it's supposed to be, so wrong indexing likely isn't the issue.

Here's the array I get from

Blue/Red: `[37, 5, 16, 35, 125, 51, 187, 1, 24, 131, 96, 1, 120, 93, 65, 187, 222, 1, 153, 98, 1, 76, 73, 11, 180, 2, 165, 1, 150, 164, 1, 137, 135, 135, 66, 108, 117, 101, 47, 82, 101, 100, 32, 69, 120, 97, 109, 112, 108, 101]`
Green Black: `[37, 105, 19, 101, 125, 57, 187, 1, 131, 9, 21, 120, 93, 1, 178, 221, 1, 139, 154, 165, 1, 131, 129, 144, 38, 1, 139, 26, 3, 187, 1, 160, 1, 71, 114, 101, 101, 110, 47, 66, 108, 97, 99, 107, 32, 69, 120, 97, 109, 112, 108, 101]`

37 (index 0) is version heroes. (37 >> 4 = 2)
Checksum then checks out too, meaning I have good reding of total card bytes.

My bug is probably somewhere later, where an expected current_index increase does or doesn't happen when it should.

**Comment by JeffAtValve** [comment] 2018-11-13 16:14
Yes your bytes look correct.  Can you post the cards you are seeing?  I also mispoke earlier, the last card is 10425 count 3 and there's only 15 cards.  My guess is either the carry bits aren't handled correctly somewhere.  The last 3 cards should be (0 indexed)

  11 => 
  array (
    'id' => 10402,
    'count' => 3,
  ),
  12 => 
  array (
    'id' => 10411,
    'count' => 3,
  ),
  13 => 
  array (
    'id' => 10418,
    'count' => 3,
  ),
  14 => 
  array (
    'id' => 10425,
    'count' => 3,
  ),

**Comment by MisterJimson** [comment] 2018-11-13 16:16
Yeah what I mean is that when they are checking ($nCurrentByteIndex <=) in PHP like on lines 175 and 186 you need to change it to ($nCurrentByteIndex <) if you are using a 0 based array.

This was causing me to get an extra card in out output before I realized that. https://github.com/MisterJimson/ArtifactDeckCodeDotNet/commit/f68759429e0780e35e3ffda4427c3eb26b911794

**Comment by JeffAtValve** [comment] 2018-11-13 16:17
Random thought, maybe you're reading into the deck name?

**Comment by JeffAtValve** [comment] 2018-11-13 16:19
Confirmed by modifying the PHP code to read 1 extra byte when parsing cards, if you are off by one on the last array you will get 10427 as the last card.

**Comment by JeffAtValve** [comment] 2018-11-13 16:43
Glad it worked! I updated the code with some comments to help others out here.  Closing this issue.

**Closed by JeffAtValve** 2018-11-13 16:43 UTC
