### ISSUE TITLE
Is there plans for tournament API / bracket embedding?

### ISSUE THREAD

**Issue by camperofcamper** [ValveSoftware/ArtifactDeckCode#38] opened 2018-12-09 10:38 UTC
Perhaps this is not the best place to ask, sorry about that. But since I don't have any other place to contact Valve devs, I will ask here.

Is there plans for tournament API? And/or bracket embedding? That would be very helpful for many sites, bots and services

**Comment by kisak-valve** [comment] 2018-12-09 13:47
Duplicate of #33.

**Closed as completed by kisak-valve** 2018-12-09 13:47 UTC
